version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000" 
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  mongo_data:
